version: '2.2'
services:
  es01:
    #image: docker.elastic.co/elasticsearch/elasticsearch:7.7.1
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.0
    container_name: es01
    environment:
      - node.name=es01
      - node.attr.rack_id=rack_one
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=es02,es03
      - cluster.initial_master_nodes=es01,es02,es03
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data01:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - elastic
    hostname: es01
  es02:
    #image: docker.elastic.co/elasticsearch/elasticsearch:7.7.1
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.0
    container_name: es02
    hostname: es02
    environment:
      - node.name=es02
      - node.attr.rack_id=rack_one
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=es01,es03
      - cluster.initial_master_nodes=es01,es02,es03
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data02:/usr/share/elasticsearch/data
    networks:
      - elastic
  es03:
    #image: docker.elastic.co/elasticsearch/elasticsearch:7.7.1
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.0
    container_name: es03
    hostname: es03
    environment:
      - node.name=es03
      - node.attr.rack_id=rack_two
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=es01,es02
      - cluster.initial_master_nodes=es01,es02,es03
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data03:/usr/share/elasticsearch/data
    networks:
      - elastic
  kib01:
    #image: docker.elastic.co/kibana/kibana:7.7.1
    image: docker.elastic.co/kibana/kibana:7.9.0
    container_name: kib01
    hostname: kib01
    ports:
      - 5601:5601
    environment:
      ELASTICSEARCH_URL: http://es01:9200
      ELASTICSEARCH_HOSTS: http://es01:9200
    networks:
      - elastic
  log01:
    #image: docker.elastic.co/logstash/logstash:7.7.1
    image: docker.elastic.co/logstash/logstash:7.9.0
    container_name: log01
    hostname: log01
    networks:
      - elastic
    volumes:
      - "./logstash/nycdata-pipe.conf:/usr/share/logstash/pipeline/nycdata-pipe.conf"
      - "./logstash/logstash.yml:/usr/share/logstash/config/logstash.yml"
      - "./logstash/pipelines.yml:/usr/share/logstash/config/pipelines.yml"
      - "./data/data.csv:/usr/share/logstash/data/data.csv"
      
volumes:
  data01:
    driver: local
  data02:
    driver: local
  data03:
    driver: local

networks:
  elastic:
    driver: bridge